### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by pavarnos** [paragonie/multi_factor#12]
Hi. Is this project still alive? 
- There have been no changes for a few years...
- Bacon QR Code is now v2 https://github.com/Bacon/BaconQrCode
- it might benefit from integration with some of your other libraries eg paragonie/hidden-string for the secret

**Comment by MrPetovan** [comment]
Bumping for curiosity.

**Comment by paragonie-scott** [comment]
I'm going to need to drastically refactor this project in the near future.

For TOTP, https://github.com/kelunik/two-factor is a great alternative for today.

In the near future, this project will be the home of a FIDO U2F implementation.

**Comment by pavarnos** [comment]
U2F would be awesome! thank you
