### ISSUE TITLE
2FA over GPG-Mailer

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/multi_factor#3]
[GPG-Mailer](https://github.com/paragonie/gpg-mailer) might be a viable 2FA strategy for GnuPG users.

**Comment by krzysztof-gzocha** [comment]
Each factor is required to implement interface `\ParagonIE\MultiFactor\MultiFactorInterface` which allows to generate and validate `string` only, but GPG-Mailer is working with `\Zend\Mail\Message`. 

Wouldn't it be better to keep it as two separate things? I mean this scenario: 
- install multi_factor and GPG-Mailer separately, 
- use already implemented FIDOU2F to generate the token,
- construct `\Zend\Mail\Message` and ensure token is inside,
- pass the message to GPG-Mailer and send.

How do you see the implementation of this issue? Got any vision for this?

**Comment by paragonie-scott** [comment]
Yeah, that's a really good point. Most of these issues were the result of a brainstorm and we weren't committing to implement all of them.

Users should be able to do what you outlined easily enough.
