### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Lewiscowles1986** [paragonie/multi_factor#7]
The licence.md contains MIT at the top, then GPL; I'm unfamiliar with this, is it dual licensed? Single licensed?

**Comment by paragonie-scott** [comment]
It's dual licensed.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/multi_factor/commit/d26a02bb0ff6123e165e9e731d10e418587117db Does this clarify it adequately?
